shouldShowStaffChat: true
staffChat:
  format: '&b[Staff-Chat] %player% → %message%'

shouldShowAdminChat: true
adminChat:
  format: '&c[Admin-Chat] %player% → %message%'

# `shouldShowEmptyLine: true` means that it will send a empty line between
# the brodcast message.
# Broadcasts a message
shouldShowBroadcast: true
broadcast:
  shouldShowEmptyLine: true
  format: '&b&lChatUtils &b%message%'

# Broadcasts a command
shouldShowCommandBroadcast: true
commandBroadcast:
  shouldShowEmptyLine: true
  format: '&b&lChatUtils &bClick to run %command%'

shouldSendMessage: true
message:
  format: '%player-from% → %player-to% &b%message%'

showTime: true
timeMessage: '%message% &b%time%'
timeZone: 'CET'

shouldBeAbleToSudo: true

# WARNING `shouldShowIp: true` shows the players ip
# if you don't want this set it to false!
shouldShowIp: false

# Replaces [item] with the player's
# held item.
showItem: true
messageToReplace: '[item]'

shouldShowEmoji: true
emojis:
  - "<3, &c❤&r"

# %word% is the message sent.
blacklistMessage: '&c&lYou are not allowed to say %word%'
blacklist:
  - fuck

blacklistAdMessage: '&c&lYou are not allowed to advertise %word%'
disabledAd:
  - hypixel


clearChat:
  format: '%player% cleared the chat'
muteChat:
  isChatNotMuted: false