name: ChatUtils
version: '${project.version}'
main: chatcontrolplus.chatcontrolplus.ChatUtils
api-version: 1.16
authors: [ zombieman ]
commands:
  staffchat:
    aliases:
      - sc
  adminchat:
    aliases:
      - ac

  clearchat:
    aliases: cc
  mutechat:
    aliases: mc
  sudo:

  chatutils:
    aliases: cu

  broadcast:
    aliases: bc
  players:

  message:
    aliases:
      - msg
      - m
      - cmsg
      - chatutilmessage
      - chatutilmsg

  command-broadcast:
    aliases:
      - cb